= Caltic Vert.x Wiki

A wiki project based on Vert.x.

== Changelog

Changelog:

* https://github.com/h3rucutu/caltic-vertx-wiki/tree/0.4.0[release-0.4.0]: Refactor using Service Proxy
* https://github.com/h3rucutu/caltic-vertx-wiki/tree/0.3.1[release-0.3.1]: Make proper documentation using README file
* https://github.com/h3rucutu/caltic-vertx-wiki/tree/0.3.0[release-0.3.0]: Add user and role management
* https://github.com/h3rucutu/caltic-vertx-wiki/tree/0.2.0[release-0.2.0]: Refactor using event bus communication
* https://github.com/h3rucutu/caltic-vertx-wiki/tree/0.1.1[release-0.1.1]: Hotfix DB Pool
* https://github.com/h3rucutu/caltic-vertx-wiki/tree/0.1.0[release-0.1.0]: Wiki Functionality
* https://github.com/h3rucutu/caltic-vertx-wiki/tree/0.0.1[release-0.0.1]: Hello World

== Prerequisites

* JDK 8+
* Git
* Docker

== Getting started

Clone this project:

[source]
----
git clone https://github.com/h3rucutu/caltic-vertx-wiki.git
----

Set Environment Variable `DATABASE_USER` and `DATABASE_PASSWORD`:

[source]
----
export DATABASE_USER=caltic_lab
export DATABASE_PASSWORD=caltic_password
----

Start PostgreSQL Database using Docker:

[source]
----
docker-compose up -d
----

Enter to bash container and create schema and seed the dummy user of vertx-auth-jdbc:

[source]
----
$ docker exec -it db_caltic_wiki sh
# psql -U caltic_lab caltic_wiki
caltic_wiki=# QUERY_INSIDE_RESOURCE
caltic_wiki=# \q
# exit
----

Replace `QUERY_INSIDE_RESOURCE` with query in https://github.com/h3rucutu/caltic-vertx-wiki/blob/master/src/main/resources/sql/vertx_auth_jdbc.sql[`vertx_auth_jdbc.sql`].

`User Matrix`

[source]
----
username | password | role   | permission
-----------------------------------------------------
admin    | admin    | admin  | create, update, delete
editor   | editor   | editor | create, update, delete
writer   | writer   | writer | update
----

== Running the project

Once you have completed every steps above, you can running with:

[source]
----
./mvnw clean compile vertx:run
----

On Windows:

[source]
----
mvnw.cmd clean compile vertx:run
----

The command compiles the project and run it in redeploy mode. Open your browser to http://localhost:9000[http://localhost:9000]. You should be redirected into login page.

Redeploy mode help developer to compile immediately when there's a changes and deploy it automatically, usually called `hot-reload`.

Besides run in redeploy mode, you also can package into one `jar` file:

[source]
----
./mvnw clean compile vertx:package
----

On Windows:

[source]
----
mvnw.cmd clean compile vertx:package
----

And run it with `java -jar` command:

[source]
----
java -jar target/*jar
----

== Heroku Live Test

This project is automated deploy with heroku pipeline.

Branch master https://caltic-wiki.herokuapp.com[caltic-wiki.herokuapp.com]

Branch develop https://caltic-wiki-test.herokuapp.com[caltic-wiki-test.herokuapp.com]

== What inside the Project?
The technology used on this Project:

* Vert.x stack (core, web, jdbc-auth, freemarker, unit).
* txtmark
* reactiverse (reactive-pg-client, vertx-maven-plugin)
* logback-classic
* junit

== Git-Flow

This project is maintained using https://github.com/nvie/gitflow[git-flow]. Please refer `git-flow` website for the instructions.

== TODO

TODO List:

* Modify https://github.com/h3rucutu/caltic-vertx-wiki/blob/master/docker-compose.yml[`docker-compose.yml`] to support running apps inside container.
* Create automated seeding user and roles database.

== Caltic.id

This project brought to you by https://caltic.id[caltic.id]
